# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 23:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.CharField(max_length=18, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('industry', models.CharField(max_length=75)),
                ('state', models.CharField(max_length=25)),
                ('size', models.IntegerField()),
                ('nonprofit', models.BooleanField()),
                ('govt_contractor', models.BooleanField()),
                ('new_england', models.BooleanField()),
                ('mid_atlantic', models.BooleanField()),
                ('south_atlantic', models.BooleanField()),
                ('south_cental', models.BooleanField()),
                ('east_central', models.BooleanField()),
                ('west_central', models.BooleanField()),
                ('mountain', models.BooleanField()),
                ('pacific', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Life',
            fields=[
                ('id', models.CharField(max_length=18, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=18)),
                ('multiple', models.FloatField()),
                ('multiple_max', models.IntegerField()),
                ('flat_amount', models.IntegerField()),
                ('add', models.BooleanField()),
                ('cost_share', models.CharField(max_length=19)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.Employer')),
            ],
        ),
    ]
