# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 03:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.CharField(max_length=18, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('alias', models.CharField(max_length=100)),
                ('broker', models.CharField(max_length=75)),
                ('industry1', models.CharField(max_length=75)),
                ('industry2', models.CharField(max_length=75)),
                ('industry3', models.CharField(max_length=75)),
                ('state', models.CharField(max_length=25)),
                ('size', models.IntegerField(blank=True, null=True)),
                ('nonprofit', models.BooleanField()),
                ('govt_contractor', models.BooleanField()),
                ('new_england', models.BooleanField()),
                ('mid_atlantic', models.BooleanField()),
                ('south_atlantic', models.BooleanField()),
                ('south_cental', models.BooleanField()),
                ('east_central', models.BooleanField()),
                ('west_central', models.BooleanField()),
                ('mountain', models.BooleanField()),
                ('pacific', models.BooleanField()),
                ('med_count', models.IntegerField()),
                ('den_count', models.IntegerField()),
                ('vis_count', models.IntegerField()),
                ('life_count', models.IntegerField()),
                ('std_count', models.IntegerField()),
                ('ltd_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Life',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=18)),
                ('multiple', models.FloatField(blank=True, null=True)),
                ('multiple_max', models.IntegerField(blank=True, null=True)),
                ('flat_amount', models.IntegerField(blank=True, null=True)),
                ('add', models.BooleanField()),
                ('cost_share', models.CharField(max_length=19)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.Employer')),
            ],
            options={
                'verbose_name_plural': 'Life Plans',
            },
        ),
        migrations.CreateModel(
            name='STD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_cont', models.BooleanField()),
                ('waiting_days', models.IntegerField(blank=True, null=True)),
                ('waiting_days_sick', models.IntegerField(blank=True, null=True)),
                ('duration_weeks', models.IntegerField(blank=True, null=True)),
                ('percentage', models.IntegerField(blank=True, null=True)),
                ('weekly_max', models.IntegerField(blank=True, null=True)),
                ('cost_share', models.CharField(max_length=19)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.Employer')),
            ],
            options={
                'verbose_name_plural': 'STD Plans',
            },
        ),
    ]
