# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 00:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='size',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='life',
            name='flat_amount',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='life',
            name='multiple',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='life',
            name='multiple_max',
            field=models.IntegerField(blank=True),
        ),
    ]
