# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 03:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='alias',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employer',
            name='broker',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='employer',
            name='den_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='employer',
            name='industry1',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='employer',
            name='industry2',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='employer',
            name='industry3',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='employer',
            name='life_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='employer',
            name='ltd_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='employer',
            name='med_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='employer',
            name='state',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='employer',
            name='std_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='employer',
            name='vis_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='life',
            name='cost_share',
            field=models.CharField(blank=True, max_length=19, null=True),
        ),
        migrations.AlterField(
            model_name='std',
            name='cost_share',
            field=models.CharField(blank=True, max_length=19, null=True),
        ),
    ]
