# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 01:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_auto_20170205_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='life',
            name='flat_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='life',
            name='multiple',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='life',
            name='multiple_max',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
